name: build-action-file-receiver Assembly Jar

on:
  workflow_dispatch:
   push:
     branches: [ main ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PUT_URI: ${{vars.PUT_URI}}
  SBT_OPTS: "-Xmx1G -XX:+UseSerialGC"

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 24
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Publish Über Jar & Deploy
      run: sbt buildActionFileReceiverUploadAssembly
