name: build-action-file-receiver Assembly Jar

on:
  workflow_dispatch:
   push:
     branches: [ main ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PUT_URI: ${{vars.PUT_URI}}
  SBT_OPTS: "-Xmx1G -XX:+UseSerialGC"

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Publish Über Jar & Deploy
      run: sbt buildActionFileReceiverUploadAssembly
