name: Publish Über Assembly to Github Packages

on:
  workflow_dispatch:
   push:
     branches: [ main ]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  PRIVATE_REPO_OAUTH: ${{secrets.PRIVATE_REPO_OAUTH}}
  POST_URI: "http://172.81.182.36:8080/releases"

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Publish Über Jar to Github Packages and Upload by Post
      run: sbt publishAssemblyToGithubPackages uploadAssemblyByPost
